apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lugx-gaming-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Rule for the game-service
      - path: /api/games
        pathType: Prefix
        backend:
          service:
            name: game-service
            port:
              number: 5001

      # Rule for the order-service
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 5002
     
      # Rule for the analytics-service
      - path: /api/track
        pathType: Prefix
        backend:
          service:
            name: analytics-service
            port:
              number: 5003

      # Rule for the frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
